name: Action Workflow1.0

on: 
  push:
  schedule: 
    - cron: "0/1 * * * *"   # (every 1mins)
    - cron: "0/8 * * * *"   # (every 8mins)
  #pull_request:
    #types: [opened, closed, reopened, assigned ]  

jobs:
  runs-github-actions:  
    runs-on: ubuntu-latest
    env: 
        platform: GitHub
        region: Asia-India
        profile-path: profile/
    
    steps: 
      -  name: show custom env 
         if: ${{ env.platform == GitHub }}
         run: |
           echo "The Platform is ${{ env.platform }}"
           echo "the region is $region " 
    
