name: Action Workflow1

on: 
  #push:
  schedule: 
    - cron: "0/2 * * * *"   # (every 2mins)
    - cron: "0/4 * * * *"   # (every 4mins)
  pull_request:
    types: [opened, closed, reopened, assigned ]  

jobs:
  runs-github-actions:  
    runs-on: ubuntu-latest
    env: 
        platform: GitHub
        region: Asia-India
        profile-path: profile/
    
    steps: 
      -  name: show custom env 
         if: ${{ env.platform == "GitHub"}}
         run: |
           echo "The Platform is ${{ env.platform }}"
           echo "the region is $region " 
    
